### ISSUE TITLE
Is this compatible with webpack 2?

### ISSUE THREAD

**Issue by davidfurlong** [code-chris/lodash-loader#6]
I cant get `{ test: /\.js$/, loader: "babel-loader!lodash-loader" }` to work, 

```
Module not found: Error: Can't resolve 'babel-loader!lodash-loader' in ...
```

**Comment by code-chris** [comment]
Hi @davidfurlong,
yes it is compatible with webpack 2. Is this a error at runtime or at compile time? How are your lodash imports look like?

**Comment by davidfurlong** [comment]
@code-chris thanks for the quick response - its a compile time error. I've since shuffled around my config to get things to work without this library.. My lodash imports in my codebase? they looked like
```
import _ from 'lodash';
``
but I've since moved to manually importing `import _pick from 'lodash/pick';`

**Comment by code-chris** [comment]
Do you create the resolve alias?
```
resolve: {
    alias: createLodashAliases()
}
```

Is there a alias for "lodash" as whole library too? Can you post your package.json?

**Comment by davidfurlong** [comment]
I tried to do this, but it's unclear how this is supposed to work with
existing aliases. I destructured it in the alias object as so `alias: {
handlebars: ... , ...createLodashAliases()}
On 9 Jun 2017 10:12 am, "Christian Kotzbauer" <notifications@github.com>
wrote:

Do you create the resolve alias?

resolve: {
    alias: createLodashAliases()
}

Is there a alias for "lodash" as whole library too? Can you post your
package.json?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/code-chris/lodash-loader/issues/6#issuecomment-307325552>,
or mute the thread

**Comment by code-chris** [comment]
Extend the object with lodash or underscore:
```
alias: {
    _.extend({ ...existing... }, createLodashAliases())
}
```

**Comment by davidfurlong** [comment]
Es6 destructing supports this without an external library using
destructured syntax or object.assign

**Comment by code-chris** [comment]
Closing for now
